Models
CotalkerPartners/cotalker-sdk pull request #1
Opened 2023-02-01 19:12 UTC by valntna

Refactoring, con ESLint agregado, y quitando los PostBody que fueron considerados innecesarios

2023-02-02 13:51 UTC, martinmiranda14 approved these changes
Ver como construir quizas una interface o clase padre para reutilizar codigo pero se ve todo bn

2023-02-02 13:51 UTC, martinmiranda14 commented on src/customTypes/COTTypes/COTSurveyAPI.ts
> +Debiese haber un tipo general para el survey, api o no? Es una idea nada mas, no esta implementado.
Comentarios en ingles (Dado que ya estaba si hay tiempo traducir )

2023-02-02 13:55 UTC, MiikeVi commented on src/customTypes/COTTypes/APIGenerics.ts
> +  path: `/${string}`, value?: unknown
```suggestion
  op: 'add' | 'remove' | 'replace' | 'move' | 'copy' | 'test',
  path: `/${string}`,
  value?: unknown,
```

2023-02-02 13:58 UTC, MiikeVi commented on src/customTypes/COTTypes/COTAnswer.ts
> +import { COTQuestionContentType } from './COTQuestion'
```suggestion
import { COTQuestionContentType } from './COTQuestion';
```

2023-02-02 13:58 UTC, MiikeVi commented on src/customTypes/COTTypes/COTAnswer.ts
> +import { ObjectId } from '@customTypes/custom'
idem

2023-02-02 13:59 UTC, MiikeVi commented on src/customTypes/COTTypes/COTChannel.ts
> +import { ObjectId } from '@customTypes/custom'
Falta semicolon en todos los import, tienes el lintern instalado?

2023-02-02 14:02 UTC, MiikeVi commented on src/customTypes/COTTypes/COTSurvey.ts
> +  code: string
linting

2023-02-02 14:06 UTC, MiikeVi commented on src/customTypes/COTTypes/COTSurveyAPI.ts
> +*/
Acostumbramos a escribir comentarios en inglés también

2023-02-02 14:21 UTC, MiikeVi commented on src/customTypes/COTTypes/COTSurveyAPI.ts
> +    subproperties: object[] | ObjectId | string
```suggestion
    subproperties: Record<string, any>[] | ObjectId | string,
```
Usamos un tipado más fuerte en vez de object, a pesar de que usar any no es muy bueno.
https://itnext.io/use-typescript-record-types-for-better-code-ce1768c6cb53

2023-02-02 14:22 UTC, MiikeVi commented on src/customTypes/COTTypes/COTTask.ts
> +}
Falta lintern

2023-02-03 12:05 UTC, Yiakman commented on src/customTypes/COTTypes/COTChannel.ts
> +import { ObjectId } from '@customTypes/custom'
transpilador agrega los punto y coma necesarios. Hay algo en particular en los import que requiera semicolon?

2023-02-03 13:21 UTC, MiikeVi commented on src/customTypes/COTTypes/COTChannel.ts
> +import { ObjectId } from '@customTypes/custom'
Mayoritariamente estilo de código, usamos esas convenciones/reglas de escritura de código en todos los proyectos

2023-02-03 13:45 UTC, MiikeVi requested changes

2023-02-03 13:45 UTC, MiikeVi commented on src/utils/HttpClient.ts
> +  private waitTime
Tipificación, creo e esto también lo marcaría el lintern

2023-02-03 13:45 UTC, MiikeVi commented on src/libs/models/COTUserClient.ts
> +  public async getSubordiantes(user: COTUser): Promise<COTUser[]> {
typo subordinates

2023-02-03 21:21 UTC, MiikeVi commented on package.json
> +    "eslint-config-airbnb-typescript": "^17.0.0"
instalar como dev dependencies

2023-02-09 17:56 UTC, MiikeVi approved these changes

2023-02-28 18:25 UTC, closed without merging